<?php
if ( ! defined('ABSPATH') ) {
  exit;
}

?>
<div id="omnivalt-settings-root" class="omnivalt-settings-page is-layout-pending">
  <header class="omnivalt-settings-page__header">
    <div class="omnivalt-settings-page__header-content">
      <div>
        <div class="omnivalt-settings-page__breadcrumb">
          <span><?php esc_html_e('WooCommerce', 'omnivalt'); ?></span>
          <span class="omnivalt-settings-page__breadcrumb-sep" aria-hidden="true">/</span>
          <span><?php esc_html_e('Omniva', 'omnivalt'); ?></span>
        </div>
        <h1 class="omnivalt-settings-page__title"><?php esc_html_e('Omniva settings', 'omnivalt'); ?></h1>
        <p class="omnivalt-settings-page__subtitle"><?php esc_html_e('Configure Omniva shipping methods, delivery services and labels.', 'omnivalt'); ?></p>
      </div>

    </div>
  </header>

  <div class="omnivalt-settings-page__layout">
    <nav class="omnivalt-settings-page__tabs omniva-tabs" aria-label="<?php esc_attr_e('Omniva settings sections', 'omnivalt'); ?>">
      <?php foreach ( $page_data['tabs'] as $tab_key => $tab_title ) : ?>
        <?php $is_active_tab = $page_data['active_tab'] === $tab_key; ?>
        <button type="button" class="omniva-tabs__tab<?php echo $is_active_tab ? ' is-active' : ''; ?>" data-settings-tab="<?php echo esc_attr($tab_key); ?>"<?php echo $is_active_tab ? ' aria-current="page"' : ''; ?>><?php echo esc_html($tab_title); ?></button>
      <?php endforeach; ?>
    </nav>

    <main class="omnivalt-settings-page__main woocommerce">
      <?php WC_Admin_Settings::show_messages(); ?>

      <form method="post" action="<?php echo esc_url($page_data['form_action']); ?>">
        <?php wp_nonce_field('woocommerce-settings'); ?>

        <?php foreach ( $page_data['cards'] as $card ) : ?>
          <?php if ( 'shipping_methods' === $card['type'] ) : ?>
            <section class="omnivalt-settings-page__card omniva-shipping-methods-card" data-settings-card="<?php echo esc_attr($card['key']); ?>" data-settings-tab="<?php echo esc_attr($card['tab']); ?>">
              <div class="omnivalt-settings-page__card-header">
                <div class="title">
                  <div class="omnivalt-settings-page__card-header-top">
                    <span class="omnivalt-settings-page__card-header-icon dashicons dashicons-<?php echo esc_attr($card['icon']); ?>" aria-hidden="true"></span>
                    <h2><?php echo esc_html($card['title']); ?></h2>
                  </div>
                </div>
              </div>
              <div class="omnivalt-settings-page__card-body">
                <div class="omniva-shipping-methods-layout" data-omniva-shipping-layout>
                  <?php foreach ( $card['methods'] as $method ) : ?>
                    <article class="omniva-shipping-method<?php echo $method['is_international'] ? ' omniva-shipping-method--international' : ''; ?>" data-omniva-method-group data-method-key="<?php echo esc_attr($method['key']); ?>">
                      <div class="omniva-shipping-method__control">
                        <?php if ( $method['is_international'] ) : ?>
                          <h3><?php echo esc_html($method['title']); ?></h3>
                          <p><?php echo esc_html($method['description']); ?></p>
                        <?php else : ?>
                          <table class="form-table omniva-settings">
                            <?php // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WooCommerce's escaped settings field renderer. ?>
                            <?php echo $method['rows_html']; ?>
                          </table>
                        <?php endif; ?>
                      </div>
                      <div class="omniva-shipping-method__countries" data-method-countries>
                        <?php if ( ! $method['is_international'] ) : ?>
                          <h3><?php esc_html_e('Delivery countries', 'omnivalt'); ?></h3>
                          <p><?php esc_html_e('Choose the countries where this shipping method should be available.', 'omnivalt'); ?></p>
                        <?php endif; ?>
                        <div class="omniva-shipping-method__country-tabs" data-method-country-tabs role="tablist" aria-label="<?php echo esc_attr($method['is_international'] ? __('International services', 'omnivalt') : __('Delivery countries', 'omnivalt')); ?>">
                          <?php foreach ( $method['destinations'] as $destination ) : ?>
                            <div class="omniva-delivery-country-tab" data-omniva-country-tab data-omniva-destination-id="<?php echo esc_attr($destination['id']); ?>" role="presentation">
                              <button type="button" class="omniva-delivery-country-tab__button" id="<?php echo esc_attr($destination['tab_id']); ?>" role="tab" aria-controls="<?php echo esc_attr($destination['id']); ?>" aria-selected="false" tabindex="-1">
                                <span class="omniva-delivery-country-tab__title">
                                  <?php if ( $destination['image_url'] ) : ?>
                                    <img class="omniva-delivery-country__flag" src="<?php echo esc_url($destination['image_url']); ?>" alt="" />
                                  <?php endif; ?>
                                  <span><?php echo esc_html($destination['title']); ?></span>
                                </span>
                              </button>
                              <span class="omniva-delivery-country-tab__toggle" data-omniva-country-toggle-wrap>
                                <?php if ( 'plan' === $destination['type'] ) : ?>
                                  <span class="switcher" title="<?php echo esc_attr($destination['title']); ?>">
                                    <label class="switch">
                                      <input type="checkbox" class="omniva-international-toggle" data-omniva-destination-toggle />
                                      <span class="slider round"></span>
                                    </label>
                                  </span>
                                <?php elseif ( ! empty($destination['blocks'][0]['toggle_html']) ) : ?>
                                  <?php // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by the shipping settings field renderer. ?>
                                  <?php echo $destination['blocks'][0]['toggle_html']; ?>
                                <?php endif; ?>
                              </span>
                            </div>
                          <?php endforeach; ?>
                        </div>
                        <div class="omniva-shipping-method__country-list" data-method-country-list>
                          <?php foreach ( $method['destinations'] as $destination ) : ?>
                            <table class="form-table omniva-settings omniva-delivery-country" id="<?php echo esc_attr($destination['id']); ?>" data-omniva-destination data-destination-type="<?php echo esc_attr($destination['type']); ?>" data-destination-key="<?php echo esc_attr($destination['key']); ?>" role="tabpanel" aria-labelledby="<?php echo esc_attr($destination['tab_id']); ?>" aria-hidden="true" hidden>
                              <tbody>
                                <tr>
                                  <td>
                                    <div class="omniva-delivery-country__box">
                                      <div class="omniva-delivery-country__header omniva-delivery-country__destination-header">
                                        <span class="omniva-delivery-country__title">
                                          <?php if ( $destination['image_url'] ) : ?>
                                            <img class="omniva-delivery-country__flag" src="<?php echo esc_url($destination['image_url']); ?>" alt="" />
                                          <?php endif; ?>
                                          <span><?php echo esc_html($destination['title']); ?></span>
                                        </span>
                                      </div>
                                      <div class="omniva-delivery-country__body" data-destination-body>
                                        <?php foreach ( $destination['blocks'] as $block ) : ?>
                                          <?php if ( 'plan' === $destination['type'] ) : ?>
                                            <div class="omniva-delivery-country__header omniva-delivery-country__method-header">
                                              <?php // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by the shipping settings field renderer. ?>
                                              <?php echo $block['toggle_html']; ?>
                                            </div>
                                          <?php endif; ?>
                                          <?php // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by the shipping settings field renderer. ?>
                                          <?php echo $block['block_html']; ?>
                                        <?php endforeach; ?>
                                      </div>
                                    </div>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          <?php endforeach; ?>
                        </div>
                      </div>
                    </article>
                  <?php endforeach; ?>

                  <?php if ( $card['returns_html'] ) : ?>
                    <div class="omniva-shipping-methods__returns">
                      <table class="form-table omniva-settings">
                        <?php // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WooCommerce's escaped settings field renderer. ?>
                        <?php echo $card['returns_html']; ?>
                      </table>
                    </div>
                  <?php endif; ?>

                </div>
              </div>
            </section>
          <?php else : ?>
            <section class="omnivalt-settings-page__card" data-settings-card="<?php echo esc_attr($card['key']); ?>"<?php echo $card['tab'] ? ' data-settings-tab="' . esc_attr($card['tab']) . '"' : ''; ?>>
              <div class="omnivalt-settings-page__card-header">
                <div class="title">
                  <div class="omnivalt-settings-page__card-header-top">
                    <span class="omnivalt-settings-page__card-header-icon dashicons dashicons-<?php echo esc_attr($card['icon']); ?>" aria-hidden="true"></span>
                    <h2><?php echo esc_html($card['title']); ?></h2>
                  </div>
                  <?php if ( $card['description'] ) : ?>
                    <p class="omnivalt-settings-page__card-subtitle"><?php echo esc_html($card['description']); ?></p>
                  <?php endif; ?>
                </div>
              </div>
              <div class="omnivalt-settings-page__card-body">
                <?php if ( 'api' === $card['section_key'] ) : ?>
                  <aside class="omnivalt-api-access" aria-label="<?php esc_attr_e('API access information', 'omnivalt'); ?>">
                    <img class="omnivalt-api-access__icon" src="<?php echo esc_url(OMNIVALT_URL . 'assets/img/admin/key.svg'); ?>" alt="" aria-hidden="true" />
                    <div class="omnivalt-api-access__content">
                      <h3><?php esc_html_e('Need API access?', 'omnivalt'); ?></h3>
                      <p><?php esc_html_e('API credentials are issued by Omniva. Contact support team to get access.', 'omnivalt'); ?></p>
                    </div>
                    <a class="omnivalt-api-access__action" href="<?php echo esc_url('https://www.omniva.lt/verslas/kontaktai-verslui'); ?>" target="_blank" rel="noopener noreferrer">
                      <?php esc_html_e('Contact Omniva', 'omnivalt'); ?>
                      <span class="dashicons dashicons-external" aria-hidden="true"></span>
                    </a>
                  </aside>
                <?php endif; ?>
                <table class="form-table omniva-settings">
                  <?php // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WooCommerce's escaped settings field renderer. ?>
                  <?php echo $card['rows_html']; ?>
                </table>
              </div>
            </section>
          <?php endif; ?>
        <?php endforeach; ?>

        <div class="omnivalt-settings-page__savebar">
          <div
            class="omnivalt-settings-page__save-status is-saved"
            data-settings-save-status
            data-saved-label="<?php esc_attr_e('All changes saved', 'omnivalt'); ?>"
            data-unsaved-label="<?php esc_attr_e('Unsaved changes', 'omnivalt'); ?>"
            role="status"
            aria-live="polite"
          >
            <span class="omnivalt-settings-page__save-status-dot" data-settings-save-status-dot aria-hidden="true"></span>
            <span data-settings-save-status-text><?php esc_html_e('All changes saved', 'omnivalt'); ?></span>
          </div>
          <div class="omnivalt-settings-page__save-notices" data-settings-save-notices aria-live="polite"></div>
          <div class="omnivalt-settings-page__save-actions">
            <button type="button" class="omnivalt-settings-page__discard" data-settings-discard hidden>
              <?php esc_html_e('Discard', 'omnivalt'); ?>
            </button>
            <button type="submit" name="save" class="woocommerce-save-button" value="<?php esc_attr_e('Save changes', 'omnivalt'); ?>" disabled>
              <?php esc_html_e('Save settings', 'omnivalt'); ?>
            </button>
          </div>
        </div>
      </form>
    </main>

    <aside class="omnivalt-settings-page__sidebar">
      <div class="omnivalt-settings-page__support-image">
        <img src="<?php echo esc_url(OMNIVALT_URL . 'assets/img/admin/support.png'); ?>" alt="<?php esc_attr_e('Omniva support', 'omnivalt'); ?>" />
      </div>

      <section class="omnivalt-settings-page__sidebar-card omnivalt-settings-page__help-card">
        <h2><?php esc_html_e('Need help?', 'omnivalt'); ?></h2>
        <p><?php esc_html_e('Have any suggestions or problems?', 'omnivalt'); ?></p>
        <p><?php esc_html_e('Please do not hesitate to', 'omnivalt'); ?> <a href="mailto:support@example.com"><?php esc_html_e('contact us', 'omnivalt'); ?></a>.</p>
      </section>

      <section class="omnivalt-settings-page__sidebar-card omnivalt-settings-page__news-card">
        <h2><?php esc_html_e('News!', 'omnivalt'); ?></h2>
        <p><?php esc_html_e('We are working on new features and improvements for your shipping experience.', 'omnivalt'); ?></p>
        <p><?php esc_html_e('Check back soon for the latest updates.', 'omnivalt'); ?></p>
      </section>

      <a class="omnivalt-settings-page__brand" href="<?php echo esc_url('https://www.omniva.lt/'); ?>" target="_blank" rel="noopener noreferrer" aria-label="<?php esc_attr_e('Omniva - Delivering Happiness', 'omnivalt'); ?>">
        <img
          class="omnivalt-settings-page__brand-logo"
          src="<?php echo esc_attr('data:image/svg+xml;charset=utf-8,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 fill=%27none%27 viewBox=%270 0 275 60%27%3E%3Cpath fill=%27%23F86300%27 d=%27M22.064 17.42C9.29 17.42 0 26.71 0 38.71S9.29 60 22.064 60C34.84 60 44.13 50.71 44.13 38.71s-9.29-21.29-22.065-21.29Zm0 34.45c-7.354 0-12.774-5.419-12.774-13.16 0-7.743 5.42-13.162 12.774-13.162 7.355 0 12.775 5.42 12.775 13.162 0 7.741-5.42 13.16-12.775 13.16m79.226-34.45c-10.84 0-14.323 8.128-14.323 8.128h-.387s-2.71-8.129-12.774-8.129c-8.904 0-12.387 7.355-12.387 7.355h-.387l-.387-6.194h-8.517v40.259h8.904V37.16c0-6.968 5.032-11.613 10.451-11.613 5.032 0 8.13 2.71 8.13 8.904v24.387h8.903V37.16c0-6.968 5.031-11.613 10.45-11.613 5.033 0 8.13 3.097 8.13 8.904v24.387h8.903V34.064c0-10.451-5.806-16.645-14.709-16.645Zm48.392 0c-9.678 0-13.161 7.354-13.161 7.354h-.387l-.388-6.194h-8.516v40.259h8.904V37.16c0-6.58 5.419-11.613 11.612-11.613 5.419 0 8.904 3.097 8.904 8.904v24.387h8.903V34.064c0-10.064-6.194-16.645-15.871-16.645Zm27.101 41.418h8.903V18.58h-8.903zM181.196 0c-2.865 0-5.187 1.935-5.187 5.265 0 3.251 2.322 5.187 5.187 5.187 2.942 0 5.265-1.936 5.265-5.187 0-3.33-2.323-5.265-5.265-5.265m33.137 46.064h-.387l-12-27.484h-9.291l17.42 40.258h8.129l17.419-40.258h-9.29zm42.404-28.645c-10.219 0-16.068 5.066-16.068 5.066v8.13h1.161s4.843-5.067 13.746-5.067c6.194 0 9.678 3.097 9.678 8.516v3.484s-4.258-2.71-11.613-2.71c-9.678 0-15.097 5.42-15.097 13.007 0 6.736 5.419 12.155 13.549 12.155 10.064 0 12.774-7.355 12.774-7.355h.387l.387 6.193h8.516V33.677c0-10.064-6.193-16.258-17.42-16.258m-2.709 34.838c-3.871 0-6.194-1.935-6.194-5.418 0-3.485 2.71-5.807 7.355-5.807 6.968 0 10.065 2.71 10.065 2.71s-1.936 8.515-11.226 8.515%27/%3E%3C/svg%3E'); ?>"
          alt=""
        />
        <span class="omnivalt-settings-page__brand-slogan">
          <?php esc_html_e('DELIVERING', 'omnivalt'); ?><br />
          <?php esc_html_e('HAPPINESS', 'omnivalt'); ?>
        </span>
      </a>
    </aside>
  </div>
</div>
